[package]
name = "grabbing-the-weather"
version = "0.1.0"
authors = ["cjstehno <chris@stehno.com>"]

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
console = "0.5.0"
reqwest = "0.8.0"
serde_json = "1.0.4"